ALL_CASES = [
    {
        "id": 1,
        "msg": "I sent 3000 to wrong number",
        "channel": "app",
        "locale": "en",
        "expected_type": "wrong_transfer",
        "expected_severity": "high",
        "expected_dept": "dispute_resolution",
        "expected_hr": True,
        "is_pdf": True,
        "is_edge": False,
        "note": "PDF sample 1 — basic wrong transfer"
    },
    {
        "id": 2,
        "msg": "Payment failed but balance deducted",
        "channel": "app",
        "locale": "en",
        "expected_type": "payment_failed",
        "expected_severity": "high",
        "expected_dept": "payments_ops",
        "expected_hr": False,
        "is_pdf": True,
        "is_edge": False,
        "note": "PDF sample 2 — basic payment failed"
    },
    {
        "id": 3,
        "msg": "Someone called asking my OTP, is that bKash?",
        "channel": "call_center",
        "locale": "en",
        "expected_type": "phishing_or_social_engineering",
        "expected_severity": "critical",
        "expected_dept": "fraud_risk",
        "expected_hr": True,
        "is_pdf": True,
        "is_edge": False,
        "note": "PDF sample 3 — basic phishing"
    },
    {
        "id": 4,
        "msg": "Please refund my last transaction, I changed my mind",
        "channel": "app",
        "locale": "en",
        "expected_type": "refund_request",
        "expected_severity": "low",
        "expected_dept": "customer_support",
        "expected_hr": False,
        "is_pdf": True,
        "is_edge": False,
        "note": "PDF sample 4 — basic refund"
    },
    {
        "id": 5,
        "msg": "App crashed when I opened it",
        "channel": "app",
        "locale": "en",
        "expected_type": "other",
        "expected_severity": "low",
        "expected_dept": "customer_support",
        "expected_hr": False,
        "is_pdf": True,
        "is_edge": False,
        "note": "PDF sample 5 — basic other"
    },
    {
        "id": 6,
        "msg": "Amar account theke taka kete neowa hoyeche kintu payment hoini",
        "channel": "sms",
        "locale": "bn",
        "expected_type": "payment_failed",
        "expected_severity": "high",
        "expected_dept": "payments_ops",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Bengali — payment failed in Bangla"
    },
    {
        "id": 7,
        "msg": "I think I sent money to wrong bKash number by mistake, please reverse it immediately",
        "channel": "app",
        "locale": "en",
        "expected_type": "wrong_transfer",
        "expected_severity": "high",
        "expected_dept": "dispute_resolution",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Polite phrasing — still wrong transfer"
    },
    {
        "id": 8,
        "msg": "Someone claiming to be bKash agent asked me to share my PIN to unlock my account",
        "channel": "call_center",
        "locale": "en",
        "expected_type": "phishing_or_social_engineering",
        "expected_severity": "critical",
        "expected_dept": "fraud_risk",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "PIN sharing request — impersonation phishing"
    },
    {
        "id": 9,
        "msg": "I received an SMS with a link saying my bKash account is suspended, click to verify",
        "channel": "sms",
        "locale": "en",
        "expected_type": "phishing_or_social_engineering",
        "expected_severity": "critical",
        "expected_dept": "fraud_risk",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Phishing via SMS link — account suspension lure"
    },
    {
        "id": 10,
        "msg": "Merchant portal payment to vendor stuck for 3 days, need urgent resolution",
        "channel": "merchant_portal",
        "locale": "en",
        "expected_type": "payment_failed",
        "expected_severity": "high",
        "expected_dept": "payments_ops",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Merchant portal channel — stuck payment"
    },
    {
        "id": 11,
        "msg": "I want to cancel my bKash account",
        "channel": "app",
        "locale": "en",
        "expected_type": "other",
        "expected_severity": "low",
        "expected_dept": "customer_support",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Account cancellation — falls under other"
    },
    {
        "id": 12,
        "msg": "transaction failed but money got deducted twice from my bank",
        "channel": "app",
        "locale": "en",
        "expected_type": "payment_failed",
        "expected_severity": "high",
        "expected_dept": "payments_ops",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Double deduction — payment failed variant"
    },
    {
        "id": 13,
        "msg": "ami 500 taka wrong number e pathiye diyechi please help",
        "channel": "app",
        "locale": "bn",
        "expected_type": "wrong_transfer",
        "expected_severity": "high",
        "expected_dept": "dispute_resolution",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Bengali — wrong transfer in Bangla"
    },
    {
        "id": 14,
        "msg": "I got a call from 01700000000 asking for my bKash OTP and card number — I gave it",
        "channel": "call_center",
        "locale": "en",
        "expected_type": "phishing_or_social_engineering",
        "expected_severity": "critical",
        "expected_dept": "fraud_risk",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Victim already complied — OTP and card number given"
    },
    {
        "id": 15,
        "msg": "My bKash payment for electricity bill failed, the amount was deducted but bill not paid",
        "channel": "app",
        "locale": "en",
        "expected_type": "payment_failed",
        "expected_severity": "high",
        "expected_dept": "payments_ops",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Utility payment failed — amount deducted"
    },
    {
        "id": 16,
        "msg": "I want a refund for a merchant payment, the product I ordered never arrived",
        "channel": "app",
        "locale": "en",
        "expected_type": "refund_request",
        "expected_severity": "medium",
        "expected_dept": "dispute_resolution",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Disputed refund — product not received, higher severity"
    },
    {
        "id": 17,
        "msg": "bKash e login korte parchi na, password forgot",
        "channel": "app",
        "locale": "bn",
        "expected_type": "other",
        "expected_severity": "low",
        "expected_dept": "customer_support",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Bengali — forgot password, general support"
    },
    {
        "id": 18,
        "msg": "Ei number e taka pathano hoyeche: 01987654321, please return koren",
        "channel": "sms",
        "locale": "bn",
        "expected_type": "wrong_transfer",
        "expected_severity": "high",
        "expected_dept": "dispute_resolution",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Bengali SMS — wrong transfer with phone number in message"
    },
    {
        "id": 19,
        "msg": "Someone sent me a fake bKash payment screenshot and asked me to send goods before I checked",
        "channel": "merchant_portal",
        "locale": "en",
        "expected_type": "phishing_or_social_engineering",
        "expected_severity": "critical",
        "expected_dept": "fraud_risk",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Merchant fraud — fake payment screenshot scam"
    },
    {
        "id": 20,
        "msg": "My transaction limit seems to have been reduced without my permission",
        "channel": "app",
        "locale": "en",
        "expected_type": "other",
        "expected_severity": "medium",
        "expected_dept": "customer_support",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Limit change — ambiguous, general support"
    },
    {
        "id": 21,
        "msg": "I accidentally sent 50,000 taka to a wrong number, this is my entire savings please help",
        "channel": "app",
        "locale": "en",
        "expected_type": "wrong_transfer",
        "expected_severity": "high",
        "expected_dept": "dispute_resolution",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "High value wrong transfer — emotional language in message"
    },
    {
        "id": 22,
        "msg": "payment erjonno taka deduct hoye geche, kintu shop confirm koreni",
        "channel": "app",
        "locale": "mixed",
        "expected_type": "payment_failed",
        "expected_severity": "high",
        "expected_dept": "payments_ops",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Mixed locale — Banglish code-switching"
    },
    {
        "id": 23,
        "msg": "I need refund from bKash agent, he took cash but didn't add to wallet",
        "channel": "call_center",
        "locale": "en",
        "expected_type": "refund_request",
        "expected_severity": "medium",
        "expected_dept": "dispute_resolution",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Agent fraud refund — cash taken, wallet not credited"
    },
    {
        "id": 24,
        "msg": "My elderly mother was tricked into sharing her bKash PIN over the phone",
        "channel": "call_center",
        "locale": "en",
        "expected_type": "phishing_or_social_engineering",
        "expected_severity": "critical",
        "expected_dept": "fraud_risk",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Third party victim — elderly person tricked into sharing PIN"
    },
    {
        "id": 25,
        "msg": "How do I add a new bank account to bKash?",
        "channel": "app",
        "locale": "en",
        "expected_type": "other",
        "expected_severity": "low",
        "expected_dept": "customer_support",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "General how-to query — no issue"
    },
    {
        "id": 26,
        "msg": "wrong transfer and now balance is also wrong",
        "channel": "app",
        "locale": "en",
        "expected_type": "wrong_transfer",
        "expected_severity": "high",
        "expected_dept": "dispute_resolution",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Two problems in one message — wrong transfer + balance discrepancy"
    },
    {
        "id": 27,
        "msg": "I",
        "channel": "app",
        "locale": "en",
        "expected_type": "other",
        "expected_severity": "low",
        "expected_dept": "customer_support",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Minimal input — single character, must not crash"
    },
    {
        "id": 28,
        "msg": "SOMEONE STOLE MY MONEY SEND HELP IMMEDIATELY 01711111111",
        "channel": "sms",
        "locale": "en",
        "expected_type": "wrong_transfer",
        "expected_severity": "high",
        "expected_dept": "dispute_resolution",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "All caps + phone number — noisy urgent message"
    },
    {
        "id": 29,
        "msg": "bKash bKash bKash refund refund refund please please",
        "channel": "app",
        "locale": "en",
        "expected_type": "refund_request",
        "expected_severity": "low",
        "expected_dept": "customer_support",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Repetitive/spam-like input — must classify gracefully"
    },
    {
        "id": 30,
        "msg": "আমি 2000 টাকা ভুল নম্বরে পাঠিয়ে দিয়েছি, দয়া করে ফেরত দিন",
        "channel": "app",
        "locale": "bn",
        "expected_type": "wrong_transfer",
        "expected_severity": "high",
        "expected_dept": "dispute_resolution",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Pure Unicode Bengali — wrong transfer in native script"
    },
    {
        "id": 31,
        "msg": "A bKash employee called and told me to give him my OTP or my account will be hacked",
        "channel": "call_center",
        "locale": "en",
        "expected_type": "phishing_or_social_engineering",
        "expected_severity": "critical",
        "expected_dept": "fraud_risk",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Threat-based phishing — account hack threat to extract OTP"
    },
    {
        "id": 32,
        "msg": "Payment failed on the merchant portal but invoice was generated for the client",
        "channel": "merchant_portal",
        "locale": "en",
        "expected_type": "payment_failed",
        "expected_severity": "high",
        "expected_dept": "payments_ops",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Merchant invoice mismatch — payment failed but invoice exists"
    },
    {
        "id": 33,
        "msg": "I made a refund request 2 weeks ago, still no response",
        "channel": "app",
        "locale": "en",
        "expected_type": "refund_request",
        "expected_severity": "medium",
        "expected_dept": "dispute_resolution",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Delayed refund follow-up — medium severity escalation"
    },
    {
        "id": 34,
        "msg": "Transaction ta complete hoye gese but status still pending dekhacche",
        "channel": "app",
        "locale": "bn",
        "expected_type": "other",
        "expected_severity": "low",
        "expected_dept": "customer_support",
        "expected_hr": False,
        "is_pdf": False,
        "is_edge": True,
        "note": "Bengali — status mismatch, general support issue"
    },
    {
        "id": 35,
        "msg": "Wrong transfer korechi, but recipient already withdrew it — can I still get it back?",
        "channel": "app",
        "locale": "mixed",
        "expected_type": "wrong_transfer",
        "expected_severity": "high",
        "expected_dept": "dispute_resolution",
        "expected_hr": True,
        "is_pdf": False,
        "is_edge": True,
        "note": "Wrong transfer — recipient already withdrew, recovery question"
    }
]
